---
- hosts: all
  vars:
    HOME: "{{ ansible_env.HOME }}"
  tasks:
    - name: Install Nginx from homebrew
      homebrew: name={{ item }} 
                state=present
      with_items:
        - nginx

    - name: Set up nginx config directory
      file: path=/usr/local/etc/nginx/{{ item }}
            state=directory
      with_items:
        - sites-enabled

    - name: Set up %{HOME}/www
      file: path={{ ansible_env.HOME}}/www
            state=directory

    - name: Copy conf file to sites-enabled
      template: src=templates/site.jinja2
            dest=/usr/local/etc/nginx/sites-enabled/web.local

    - name: Add www.web.local to /etc/hosts
      lineinfile: dest=/etc/hosts
                  regexp='^127\.0\.0\.1' line='127.0.0.1 web.local'

    - name: Restart Nginx
      command: nginx -s reload
      become: yes
